### ISSUE TITLE
[FR] Use Timesketch import client to upload data

### ISSUE THREAD

**Issue by berggren** [LDO-CERT/mans_to_es#11] opened 2020-05-26 20:18 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to get a stream of events (dataframes) from the parser without sending them to ES.  For example, Timesketch handles ES imports on its own and would make it more consistent and preferable to handle the low level ES operations outside of this library.

**Describe the solution you'd like**
Add functionality to expose a generator of events from the parser, without exporting them to ES.

**Comment by dadokkio** [comment] 2020-05-27 08:39
Hi, that is something doable but I need to think better about this.

At the moment we use multiprocessing (billiard to be compatible with celery) to process different files that are inside .mans. Each file has different schema and format.
Each process saves temporary the processed dataframe as json and, at the end, a function picks all  json files and push them to elastic using bulk import and a queue.

We can try to provide and integration with your ES importer, but we need to understand better how to generate it properly.

**Comment by berggren** [comment] 2020-05-27 11:44
I see. I was chatting with kiddi about this and I think we have a nice solution to propose.

Instead of doing this in Timesketch (on the server side) we suggest using the Timesketch import client (standalone package) that accepts dataframes as a stream and will take care of efficiently upload the data to your TS server, and will take care of authentication etc. This way you can add a flag to mans_to_es that pushes it to Timesketch instead of ES.

Kiddi will give you some examples on how to do this integration.

What do you think?

**Comment by dadokkio** [comment] 2020-05-27 12:59
that sounds reasonable and surely example could help since i never used it before.
A question I have in mind is If I can use it in parallel and push different dataframe to the same index. Usually we have dozen of files and only few are very big. Can we push the small one before as soon as they complete the parsing?

**Comment by kiddinn** [comment] 2020-05-27 21:25
there are two things that you'll need... first of all get a `sketch` object from teh API client and then the importer client.

```
from timesketch_api_client import config
ts = config.get_client()
```

This should be sufficient to get the client object. (first time running this will ask questions that will then be saved into a config file for future references).

Then the next step is to get a sketch
```
sketch = ts.get_sketch(SKETCH_ID)
```

or create a sketch

```
sketch = ts.create_sketch(NAME, DESCRIPTION)
```

Then once you have a sketch you'll set up the import client and then import the data...

```
from timesketch_import_client import helper
from timesketch_import_client import importer

(do some magic to get data frames)

import_helper = helper.ImportHelper()

with importer.ImportStreamer() as streamer:
  streamer.set_sketch(sketch)
  streamer.set_config_helper(import_helper)
  streamer.set_timeline_name(TIMELINE_NAME)
  streamer.add_data_frame(DATA_FRAME)
```

There are other options here... such as if you want to have your own config file (YAML) to load definitions of how the dataframes should be structured/formatted then you can do

```
import_helper.add_config(FILE_PATH)
```

You can see the format of the file here: https://github.com/google/timesketch/blob/master/importer_client/python/timesketch_import_client/data/formatter.yaml

You can also not use `with` statements with the import streamer if you so desire, then you need to call `streamer.close()` to close it (with statement enforces it).

So the complete example would be:

```
from timesketch_api_client import config
from timesketch_import_client import helper
from timesketch_import_client import importer

...
ts = config.get_client()
sketch = ts.get_sketch(SKETCH_ID)
import_helper = helper.ImportHelper()

... (code to generate dataframes) ....
with importer.ImportStreamer() as streamer:
  streamer.set_sketch(sketch)
  streamer.set_config_helper(import_helper)
  streamer.set_timeline_name(TIMELINE_NAME)
  streamer.add_data_frame(DATA_FRAME)

```

or

```
streamer = importer.ImportStreamer()
streamer.set_sketch(sketch)
streamer.set_config_helper(import_helper)
streamer.set_timeline_name(TIMELINE_NAME)

for something in something:
  data_frame = get_my_frame()
  streamer.add_data_frame(data_frame)
  # more code

streamer.close()
```

**Comment by kiddinn** [comment] 2020-05-27 21:26
hopefully this will help

**Comment by dadokkio** [comment] 2020-05-28 12:34
Thanks! I tried to implement this with partials results.

I wasn't able to run the importer during multiprocessing so I processed all the xml files inside .mans and then I used add_data_frame in a for loop.

Sketch and timeline creation is working but all the timelines are stuck in "indexing in progress.." status. There is a way to debug this? Since in the docker logs I can't see anything happening.

**Comment by berggren** [comment] 2020-05-28 19:38
Hi, did you do a `streamer.close()` after your loop?

If possible, please share your testing code, a GitHub Gist for example. That would make it easier for us to help :)

**Comment by dadokkio** [comment] 2020-05-29 06:48
I'm using the context manager mode so I can forget about :)

In any case I created [a new branch](https://github.com/LDO-CERT/mans_to_es/blob/test_timesketch_api/mans_to_es/mans_to_es.py)

 The api and the sketch are defined in the class constructor while the import process is in to_timesketch() function. 

I had to comment out helpers because last available packages for timesketch_import_client [20200514] don't have them available.

**Comment by kiddinn** [comment] 2020-05-29 07:27
I will take a closer look at this shortly, but in the meantime I did update pypi with the latest clients now, so you should be able to do get the helper function now.

**Comment by dadokkio** [comment] 2020-05-29 08:01
ok, I had my celery process stuck.. Now I can see upload progresses. 
I'm going to restart everything and test the new release with helpers.
Thanks!

**Comment by dadokkio** [comment] 2020-05-29 08:51
Some updates.
I created a new sketch with some small .mans inside:
```
$mans_to_es.py --filename AAA_1.mans timesketch --sketch_name AAA --timeline_name AAA_1
$mans_to_es.py --filename AAA_2.mans timesketch --sketch_id 14 --timeline_name AAA_2
$mans_to_es.py --filename AAA_3.mans timesketch --sketch_id 14 --timeline_name AAA_3
```
![image](https://user-images.githubusercontent.com/355183/83240499-c414ff00-a199-11ea-8dc1-da7e794b8ae2.png)

The latest one is returning error in celery console and remains both available and in indexing status:
```
[2020-05-29 08:43:17,437: ERROR/ForkPoolWorker-16] Task timesketch.lib.tasks.run_csv_jsonl[4f95cc96-25b6-4def-ae01-5c319fc7a24e] raised unexpected: RequestError(400, 'resource_already_exists_exception', {'error': {'root_cause': [{'type': 'resource_already_exists_exception', 'reason': 'index [6b065f8998d945dea5e08253fafce5b6/1eQ3RTcmTdehAH0RI-bxuw] already exists', 'index_uuid': '1eQ3RTcmTdehAH0RI-bxuw', 'index': '6b065f8998d945dea5e08253fafce5b6'}], 'type': 'resource_already_exists_exception', 'reason': 'index [6b065f8998d945dea5e08253fafce5b6/1eQ3RTcmTdehAH0RI-bxuw] already exists', 'index_uuid': '1eQ3RTcmTdehAH0RI-bxuw', 'index': '6b065f8998d945dea5e08253fafce5b6'}, 'status': 400})
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/src/timesketch/timesketch/__init__.py", line 174, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/src/timesketch/timesketch/lib/tasks.py", line 502, in run_csv_jsonl
    es.create_index(index_name=index_name, doc_type=event_type)
  File "/usr/local/src/timesketch/timesketch/lib/datastores/elastic.py", line 547, in create_index
    index=index_name, body={'mappings': _document_mapping})
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/client/indices.py", line 100, in create
    "PUT", _make_path(index), params=params, body=body
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/dist-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'resource_already_exists_exception', 'index [6b065f8998d945dea5e08253fafce5b6/1eQ3RTcmTdehAH0RI-bxuw] already exists')
```
Why this his happening and how can I prevent this?

**Comment by kiddinn** [comment] 2020-05-29 21:27
sorry, I wasn't able to take a look at this today, I'll try to look at it shortly (weekend or tuesday) and give a better response.

Regarding the double state, I will need to take a closer look at that, whether that is something that we need to do in the importer state, or in your code. 

But is this happening consistently, or just once?

**Comment by dadokkio** [comment] 2020-05-31 10:13
I uploaded 53 mans to test and this happened 6 times. In 5 cases I have both data to explore and the "indexing" while the last is in error state.

**Comment by kiddinn** [comment] 2020-06-02 14:12
ok, I'm back, and I will take a look at the code right now to see if we can get this fixed

**Comment by kiddinn** [comment] 2020-06-02 14:29
can you share some sample files with me?

is this consistently behaving like this, or does it vary with each run?

**Comment by dadokkio** [comment] 2020-06-03 08:59
Ok, I rerun failed jobs and they they behaved more or less in the same way.
Then I try to explore some of the failed run and run them manually. Everything seems to be ok.
Then I tried to add a simple sleep in the loop and this seems to resolve the issue. 

```
import time
import pandas as pd
from glob import glob
from timesketch_api_client import config
from timesketch_import_client import importer
from timesketch_import_client import helper

ts = config.get_client()
sketch = ts.create_sketch("TEST")
import_helper = helper.ImportHelper()
streamer = importer.ImportStreamer()
streamer.set_sketch(sketch)
streamer.set_config_helper(import_helper)
streamer.set_timeline_name("TEST-1")
for file in glob("*.json"):
    df = pd.read_json(file, orient="records", lines=True)
    streamer.add_data_frame(df)
    time.sleep(1)
    
streamer.close()
```

Without the sleep I'm receiving the issue even in a clean docker environment

```
[2020-06-03 08:45:48,902: INFO/MainProcess] Received task: timesketch.lib.tasks.run_csv_jsonl[e8531f94-02f0-40bd-9c28-b4514820dc64]  
[2020-06-03 08:45:48,959: INFO/MainProcess] Received task: timesketch.lib.tasks.run_csv_jsonl[9fa6dd7d-3761-400a-aef2-464ee710f0d1]  
[2020-06-03 08:45:48,977: INFO/ForkPoolWorker-16] Index timeline [TEST-0] to index [2d08cf56d5514a95857d51a141ff2604] (source: jsonl)
[2020-06-03 08:45:49,021: INFO/ForkPoolWorker-15] Index timeline [TEST-0] to index [2d08cf56d5514a95857d51a141ff2604] (source: jsonl)
[2020-06-03 08:45:49,069: WARNING/ForkPoolWorker-15] PUT http://elasticsearch:9200/2d08cf56d5514a95857d51a141ff2604 [status:400 request:0.045s]
[2020-06-03 08:45:49,081: INFO/MainProcess] Received task: timesketch.lib.tasks.run_csv_jsonl[965d5312-9377-46a0-a6a0-1d352b457a7a]  
[2020-06-03 08:45:49,090: INFO/ForkPoolWorker-1] Index timeline [TEST-0] to index [2d08cf56d5514a95857d51a141ff2604] (source: jsonl)
[2020-06-03 08:45:49,116: ERROR/ForkPoolWorker-15] Task timesketch.lib.tasks.run_csv_jsonl[e8531f94-02f0-40bd-9c28-b4514820dc64] raised unexpected: RequestError(400, 'resource_already_exists_exception', {'error': {'root_cause': [{'type': 'resource_already_exists_exception', 'reason': 'index [2d08cf56d5514a95857d51a141ff2604/R_W5fqp2TqOWMpJ3w13N4Q] already exists', 'index_uuid': 'R_W5fqp2TqOWMpJ3w13N4Q', 'index': '2d08cf56d5514a95857d51a141ff2604'}], 'type': 'resource_already_exists_exception', 'reason': 'index [2d08cf56d5514a95857d51a141ff2604/R_W5fqp2TqOWMpJ3w13N4Q] already exists', 'index_uuid': 'R_W5fqp2TqOWMpJ3w13N4Q', 'index': '2d08cf56d5514a95857d51a141ff2604'}, 'status': 400})
```
Could be something related to dataframe size? the smallest one contains just 19 records (5kb)

**Comment by kiddinn** [comment] 2020-06-03 12:04
ok.. so I think this has to do with dataframe size.. that is if the dataframe is small and then a new dataframe is added immediately after there is a `race condition` in which one of the tests to see if an index already exists is not returning an accurate result.

I don't like the additions of `sleep`, since they are not really "predictable" but you can do it in your script. but can you also test: https://github.com/kiddinn/timesketch/tree/aflusun

That is I added a small exception handling to that exception, and if the index exists nad fails to be created it doesn't crash the program, it should jsut assume that there is a race condition and return the index.

**Comment by kiddinn** [comment] 2020-06-03 15:25
Let me know when you've tested this again without the `sleep` and with the new server backend to test whether this behavior still occurs.

**Comment by dadokkio** [comment] 2020-06-03 15:30
yes, it's working with a nice warning:

```
[2020-06-03 15:15:25,456: INFO/MainProcess] Received task: timesketch.lib.tasks.run_csv_jsonl[25780d6e-976a-414a-bdb7-c09eac6b3951]  
[2020-06-03 15:15:25,479: INFO/MainProcess] Received task: timesketch.lib.tasks.run_csv_jsonl[9e31dc3a-3c04-4209-b132-d2cc90aa31ee]  
[2020-06-03 15:15:25,482: INFO/ForkPoolWorker-16] Index timeline [AAA_01] to index [217d73d661404f30ab9774e9155066c6] (source: jsonl)
[2020-06-03 15:15:25,483: INFO/ForkPoolWorker-15] Index timeline [AAA_01] to index [217d73d661404f30ab9774e9155066c6] (source: jsonl)
[2020-06-03 15:15:25,674: WARNING/ForkPoolWorker-16] PUT http://elasticsearch:9200/217d73d661404f30ab9774e9155066c6 [status:400 request:0.107s]
[2020-06-03 15:15:25,680: WARNING/ForkPoolWorker-16] Attempting to create an index that already exists (217d73d661404f30ab9774e9155066c6 - True)
[2020-06-03 15:15:26,170: INFO/ForkPoolWorker-16] Task timesketch.lib.tasks.run_csv_jsonl[9e31dc3a-3c04-4209-b132-d2cc90aa31ee] succeeded in 0.6895856599985564s: '217d73d661404f30ab9774e9155066c6'
[2020-06-03 15:15:26,585: INFO/ForkPoolWorker-15] Task timesketch.lib.tasks.run_csv_jsonl[25780d6e-976a-414a-bdb7-c09eac6b3951] succeb9774e9155066c6'
[2020-06-03 15:16:09,265: INFO/MainProcess] Received task: timesketch.lib.tasks.run_csv_jsonl[6d9ce98a-092c-4b41-89c0-c1cc2f07633e]  
[2020-06-03 15:16:09,425: INFO/MainProcess] Received task: timesketch.lib.tasks.run_csv_jsonl[d419aeb1-52ee-4128-8791-e39d45e1e9dc]  
[2020-06-03 15:16:09,668: INFO/MainProcess] Received task: timesketch.lib.tasks.run_csv_jsonl[0ac5ebf2-c9fa-4840-a6d1-c0d561175bd3]  
[2020-06-03 15:16:09,685: INFO/MainProcess] Received task: timesketch.lib.tasks.run_csv_jsonl[36e4e177-c8be-493e-96e4-946dfbcffd86]  
[2020-06-03 15:16:09,691: INFO/ForkPoolWorker-2] Index timeline [AAA_01] to index [217d73d661404f30ab9774e9155066c6] (source: jsonl)
[2020-06-03 15:16:09,788: INFO/ForkPoolWorker-16] Index timeline [AAA_01] to index [217d73d661404f30ab9774e9155066c6] (source: jsonl)
[2020-06-03 15:16:10,065: INFO/ForkPoolWorker-1] Index timeline [AAA_01] to index [217d73d661404f30ab9774e9155066c6] (source: jsonl)
[2020-06-03 15:16:10,708: INFO/ForkPoolWorker-2] Task timesketch.lib.tasks.run_csv_jsonl[36e4e177-c8be-493e-96e4-946dfbcffd86] succeeb9774e9155066c6'
[2020-06-03 15:16:13,639: INFO/ForkPoolWorker-15] Index timeline [AAA_01] to index [217d73d661404f30ab9774e9155066c6] (source: jsonl)
[2020-06-03 15:16:14,488: INFO/ForkPoolWorker-16] Task timesketch.lib.tasks.run_csv_jsonl[d419aeb1-52ee-4128-8791-e39d45e1e9dc] succeb9774e9155066c6'
[2020-06-03 15:16:25,440: INFO/ForkPoolWorker-1] Task timesketch.lib.tasks.run_csv_jsonl[0ac5ebf2-c9fa-4840-a6d1-c0d561175bd3] succeeb9774e9155066c6'
[2020-06-03 15:16:42,037: INFO/ForkPoolWorker-15] Task timesketch.lib.tasks.run_csv_jsonl[6d9ce98a-092c-4b41-89c0-c1cc2f07633e] succeab9774e9155066c6'
```
I'm going to fix small details and then this should be ok.

**Comment by dadokkio** [comment] 2020-06-05 08:17
@kiddinn we are trying to integrate back the mans_to_es in timesketch but we have some doubt..
We are changing the tasks.pt function but in the run_mans [or the other similar functions] the sketch id is not provided as function argument.
How we can get the sketch_id in that case? Which is the correct procedure to follow?

**Comment by kiddinn** [comment] 2020-06-05 08:51
Ok, the typical way this is done in other tools is to have an optional `sketch_id` as a parameter to the tool, if not provided then create a sketch

```
if sketch_id:
  sketch = ts.get_sketch(sketch_id)
else
  sketch = ts.create_sketch('Mans Sketch AND SOME OTHER PARTS OF THE NAME', description='Generated by manstoes')
```

or something like this.D oes that not work?

Other tools sometimes read the sketch ID from references to SIEM tools, if they can be read as attributes, etc.. .depends on what the tool has available to it.

**Comment by kiddinn** [comment] 2020-06-05 08:52
but the PR I mentioned above has been merged with the project, so the issue you had should no longer be there.

**Comment by dadokkio** [comment] 2020-06-05 08:56
We were trying to reintegrate out code in timesketch tasks.py code in order to be able to upload the mans from the gui.
So the problem is that in that case we don't know the id or name of the sketch, and I think I shouldn't create a new one.

**Comment by kiddinn** [comment] 2020-06-05 09:24
can we take this offline, can you send me an email and we can figure out a solution here (kristinn at log2timeline.net)

**Closed** 2021-02-26 11:30 UTC
Labels: enhancement
